name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25f0a0956270381628d01115582f6e7 # v6.0.0
        with:
          node-version: 20
          package-manager-cache: false

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Merge Service Data
        run: python3 scripts/merge_services.py

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@9681c2997648301493e78cacbfb790a9f19c833f # v3.9.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=betterlb
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}